cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
	url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
	url(r'^$', views.CartDetail, name='CartDetail'),
]

kv_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('shop.urls', namespace='shop'))

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
# -*- coding: utf-8 -*-
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]
class CartAddProductForm(forms.Form):
	quantity = forms.IntegerField(initial=1, widget=forms.TextInput( attrs = {'id': 'quanity-input', 'readonly': 'readonly','style': 'width: 20px; border: none; text-align:center;'} ))
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.template.loader import render_to_string
from django.http import HttpResponse,JsonResponse

@require_POST
def CartAdd(request, product_id):
	if request.is_ajax:
		cart = Cart(request)
		product = get_object_or_404(Product, id=product_id)
		form = CartAddProductForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			print(cd)
			cart.add(product=product, quantity=cd['quantity'],
									  update_quantity=cd['update'])
			data = {
		        'total_items': len(cart),
		        'total_price': cart.get_total_price(),
		        'product_name': product.name,
		        'product_image': product.image.url,

		        
	    	}
			# return HttpResponse({'total': , 'count': cart.__iter__()})
			return JsonResponse(data)
	return HttpResponse('lox')

def CartRemove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	data = {
	'status': 'ok',
	'product_id': str(product.id),
	'items': len(cart),
	'total_price': cart.get_total_price(),
	}
	return JsonResponse(data)


def CartDetail(request):
	cart = Cart(request)
	if cart:
		for item in cart:
			if item:
				item['update_quantity_form'] = CartAddProductForm(
												initial={
													'quantity': item['quantity'],
													'update': True
												})
		return render(request, 'cart/detail.html', {'cart': cart})
	else:
		return render(request, 'cart/not.html')

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{%load static%}


{%block content%}
<style>
    #quanity-input{
        display: inline-block;

    } 
  .cart-image{
    display: block;
    margin: 0;
    float: left;
    width: 70px;
    min-width: 70px;
  }
  .cart-item-content {
    overflow: hidden;
    height: 70px;
    margin-left: 90px;
  }

  .cart-item-title {
    vertical-align: middle;
    display: inline-block;
    max-width: 98%;
    text-align: left;
  }
  .cart-item-title a{
    line-height: 5;
  }
  .cart-list {
    list-style: none;
  }
  .quanity-block {
    margin: 20px auto 0;
    max-width: 150px;
  }
  .cart-price {
    display: block;
    margin-top: 24px;
    text-align: right;
    font-size: 20px;
  }
  .cart-remove {
    display: block;
    border: 0;
    padding: 0;
    background: orange;
    color: #fff;
    font-size: 16px;
    text-align: center;
    width: 26px;
    height: 26px;
    border-radius: 30px;
    position: absolute;
    right: -20px;
    top: 50%;
    margin-top: -3px;
  }
  .cart-remove:hover {
    background-color: #fff;
    color: orange;
  }
  .cart-quanity-btn:hover {
    background-color: #fff;
    color: orange;
  }
  .cart-total {
    background-color: #f7f7f7;
    padding: 20px;
  }
  .cart-total .h5 {
    font-weight: 700;
    color: #5C5C5C;
    margin: 0 0 15px;
  }
  .cart-total .cart-total-list {
    list-style: none;
    padding: 0;
    margin: 15px 0 40px;
  }
  .cart-total a {
    color: #fff;
    text-decoration: none;
    background-color: orange;
    display: block;
    margin-top: 40px;
    width: 100%;
    max-width: 230px;
    margin-left: auto;
    margin-right: auto;
    cursor: pointer;
    line-height: 1;
    font-weight: 400;
    color: #fff;
    border: 0;
    padding: 12px 20px;
    text-align: center;
    font-family: 'Exo 2', sans-serif;
    font-size: 16px;
    -webkit-transition: all 0.2s linear;
    transition: all 0.2s linear;
    -webkit-appearance: none;
    -webkit-writing-mode: unset;
    -webkit-box-align: normal;
    -ms-flex-align: normal;
    align-items: normal;
  }
  .cart-total-list__first {
    padding-right: 4px;
  }
  .cart-total-list__dots {
    color: grey;
  }
  .cart-list__item {
    display: block;
    padding-right: 70px;
    position: relative;
    margin-bottom: 15px;
    margin-top: 15px;
    border-bottom: 1px solid #eee;
  }
  .cart-list__item:nth-child(1) {
    border-top: 1px solid #eee;
  }
  .cart-quanity-btn {
    display: inline-block;
    border: 0;
    padding: 0;
    background: orange;
    color: #fff;
    font-size: 17px;
    text-align: center;
    width: 26px;
    height: 26px;
    border-radius: 3px;
  }

</style>
<div class="checkout">
  <div class="container">

    <h3>Моя корзина</h3>
<div class="row">
    <div class="col-sm-9">
        <ul class="cart-list">
            {%for item in cart%}
            {%with product=item.product%}

            <li id="t_{{product.id}}" class="cart-item">
               <div class="cart-list__item">
                  <div class="row">
                      <div class="col-xs-12 col-sm-7 col-lg-6">
                    <img class="cart-image" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "shop/images/no-img.jpg"%}{% endif %}" alt="product-image">
                    <div class="cart-item-content">
                      <div class="cart-item-title">
                          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                      </div>
                    </div>

                </div>
                <div class="col-xs-8 col-sm-3 col-lg-4">
                  <div class="quanity-block">
                     <form id="cart_update" action="{% url "cart:CartAdd" product.id %}" method="post" class="add">{% csrf_token %}
                      <button onclick="javascript:ajaxSubmitC($(this.form), 1)" type="submit" id="quanity-minus" class="cart-quanity-btn">-</button>
                        {{ item.update_quantity_form.quantity }} 
                        {{ item.update_quantity_form.update }}
                      <button onclick="javascript:ajaxSubmitC($(this.form), 0)" type="submit" id="quanity-plus" class="cart-quanity-btn">+</button>
                    </form>
                  </div>
                   
                </div>
                <div class="col-xs-4 col-sm-2">
                  <span class="cart-price"><strong>{{product.price }} ₽</strong><a class="cart-remove" href="{% url "cart:CartRemove" product.id %}">x</a></span>
                 
                </div>
                  </div>
                </div>
                
            </li>
            {%endwith%}
            {%endfor%}
        </ul>
    </div>

    <div class="col-sm-3">
      <div class="cart-total">
        <div class="h5">Итого:</div>
        <ul class="cart-total-list">
          <li>
            <span class="cart-total-list__first"><strong>{{cart|length}}</strong> шт</span>
            <span class="cart-total-list__dots">-</span>
            <span class="cart-total-list__last"><strong>{{cart.get_total_price}}</strong>₽</span>
          </li>
        </ul>
        <a href="{% url "orders:OrderCreate" %}"><span class="glyphicon glyphicons-circle-arrow-right" aria-hidden="true"></span>Оформить</a>
      </div>
    </div>
</div>

  </div>
  <script type="text/javascript">
    
    function ajaxSubmitC(obj, action) {
        var frm = obj
        var action = parseInt(action)
        console.log(action);
        last_quanity = parseInt($( "input[name='quantity']", frm ).val());
        if (action === 0) {
          last_quanity = parseInt($( "input[name='quantity']", frm ).val(last_quanity + 1));
        } else {
          if (last_quanity === 1) {
            return false;
          } else {
            last_quanity = parseInt( $( "input[name='quantity']", frm ).val(last_quanity - 1) );
          }
          
        }

        frm.submit(function (e) {
        e.preventDefault();
        $.ajax({
            beforeSend: function() {
                $('.loading').show();
            },
            complete: function() {
                $('.loading').hide();
            },
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            dataType: "json",
            success: function (data) {
                console.log('Submission was successful.');
                $('.cart-total-list__first strong').html(data.total_items);
                $('.cart-total-list__last strong').html(data.total_price);
                $('#cart-info').html(data.total_items + ' тов. ' + data.total_price + ' ₽');
            },
            error: function (data) {
                console.log('An error occurred.');
                console.log(data);
            },
        });
    });
    };
    $('.cart-remove').click(function(e) {
      e.preventDefault();
      $.ajax({
            beforeSend: function() {
                $('.loading').show();
            },
            complete: function() {
                $('.loading').hide();
            },
            type: 'GET',
            url: $(this).attr('href'),
            dataType: "json",
            success: function (data) {
              if (data.items === 0) {
                location.reload();
              }
              $('#t_' + data.product_id).remove();
              $('.cart-total-list__first strong').html(data.items);
              $('.cart-total-list__last strong').html(data.total_price);
              $('#cart-info').html(data.items + ' тов. ' + data.total_price + ' ₽');
            },
            error: function (data) {
                console.log('An error occurred.');
                console.log(data);
            },
        });
      return false;
    })


</script>
</div>

{%endblock%}

cart/templates/cart/not.html
{% extends "shop/base.html" %}
{% block title %}
  Ваша корзина товаров пустая
{% endblock %}
{%load static%}


{%block content%}
<div class="checkout">
  <div class="container">
    <h3>Ваша корзина товаров пустая</h3>
    <div class="checkout-left"> 
        <div class="checkout-right-basket animated wow slideInRight" data-wow-delay=".5s">
          <a href="/"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>Продожить покупки</a>
        </div>
        <div class="clearfix"> </div>
      </div>
  </div>
</div>

{%endblock%}