cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
	url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
	url(r'^$', views.CartDetail, name='CartDetail'),
]

kv_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('shop.urls', namespace='shop'))

]

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^search/$', views.search, name='search'),
    url(r'^rent/$', views.rent, name='rent'),
    url(r'^service/$', views.service, name='service'),
    url(r'^contact-phone/$', views.contactPhone, name='contact-phone'),
    url(r'^contact-email/$', views.contactEmail),
    url(r'^shipping/$', views.shipping, name='shipping'),
    url(r'^garant/$', views.garant, name='garant'),
    url(r'^about/$', views.about, name='about'),
    url(r'^vozvrat/$', views.vozvrat, name='vozvrat'),

    url(r'^(?P<Cat_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<cat_slug>[-\w]+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),

    url(r'^all/$', views.ProductList, name='ProductList'),
    url(r'^$', views.MainPage, name='MainPage'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from embed_video.fields import EmbedVideoField
from tinymce.models import HTMLField
from mptt.models import MPTTModel, TreeForeignKey

class ContactEmail(models.Model):
	email = models.CharField(max_length=40, verbose_name="Email")
	def __unicode__(self):
			return self.email


class SliderItem(models.Model):
	image = models.ImageField(upload_to='products/', verbose_name="Изображение")
	title = models.CharField(max_length=80, verbose_name='Текст')
	button = models.BooleanField(verbose_name='Кнопка')
	button_text = models.CharField(max_length=20, verbose_name='Текст на кнопке', null=True, blank=True)
	button_link = models.CharField(max_length=40, verbose_name='Ссылка', null=True, blank=True)
	def __unicode__(self):
    		return self.title
	class Meta:
		verbose_name = 'Слайд'
		verbose_name_plural = 'Слайды'
	
class Rent(models.Model):
	title = models.CharField(max_length=20, verbose_name="Заголовок")
	title_t = models.CharField(max_length=200, verbose_name="Подзаголовок", blank=True, null=True)
	image = models.ImageField(upload_to='products/', verbose_name="Изображение")
	bez_zal = HTMLField(blank=True, verbose_name='Без залога')
	s_zal = HTMLField(blank=True, verbose_name='С залогом')
	class Meta:
		ordering = ['title']
		verbose_name = 'Блок аренды'
		verbose_name_plural = 'Аренда'

class InfoModel1(models.Model):
	info = HTMLField(blank=True, verbose_name='Контакты')
	rekv = HTMLField(blank=True, verbose_name="Реквизиты")
	rent = HTMLField(blank=True, verbose_name="Аренда")
	service = HTMLField(blank=True, verbose_name="Сервисный центр")
	seo_title = models.CharField(max_length=100, blank=True, default="Рекламный блок", verbose_name='Заголовок рекламного блока')
	seo = HTMLField(blank=True, verbose_name='Рекламный блок')
	email_text = HTMLField(blank=True, verbose_name='Текст подписки')
	class Meta:
		verbose_name = 'Информация'
		verbose_name_plural = 'Информация'

class InfoModel(models.Model):
	dostavka = HTMLField(blank=True, verbose_name='Курьерская доставка в подвале')
	phone = HTMLField(blank=True, verbose_name='Телефон')
	email = models.EmailField(blank=True, verbose_name='Email')
	address = models.CharField(max_length=100, blank=True, verbose_name='Адрес')
	about = models.TextField(max_length=200, blank=True, null=True)
	class Meta:
		verbose_name = 'Контакты'
		verbose_name_plural = 'Контакты'

class Review(models.Model):
	name = models.CharField(max_length=50, verbose_name='Имя')
	text = models.TextField(max_length=200, verbose_name='Текст отзыва')
	class Meta:
		verbose_name = 'Отзывы'
		verbose_name_plural = 'Отзыв'

	def __unicode__(self):
    		return 'Отзыв от ' + self.name

class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True, verbose_name='Имя категории')
	slug = models.SlugField(max_length=200, db_index=True, unique=True)
	parent = models.ForeignKey('self', blank=True, null=True, related_name='child')

	has_child = models.BooleanField(default=False, verbose_name='Выпадающее меню')

	def get_absolute_url(self):
		return reverse('shop:ProductListByCategory', args=[self.slug])
	class Meta:
		ordering = ['name']
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'

	def __unicode__(self):
		return self.name

class Cat(MPTTModel):
	name = models.CharField(max_length=50, unique=True)
	parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
	slug = models.SlugField(max_length=50, db_index=True, unique=True)
	icon = models.ImageField(upload_to='products/', blank=True, verbose_name="Иконка", null=True)
	image = models.ImageField(upload_to='products/', blank=True, verbose_name="Изображение", null=True)
	def get_absolute_url(self):
		return reverse('shop:ProductListByCategory', args=[self.slug])
	class Meta:
		verbose_name_plural = 'Kатегории'    		
	class MPTTMeta:
		order_insertion_by = ['name']

	def __unicode__(self):
		return self.name

class Product(models.Model):
	category = models.ForeignKey(Cat, related_name='products', verbose_name="Категория", null=True, blank=True)
	name = models.CharField(max_length=54, db_index=True, verbose_name="Название (макс. длина 54 символов)")
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField(upload_to='products/', blank=True, verbose_name="Изображение товара1", null=True)
	image2 = models.ImageField(upload_to='products/', blank=True, verbose_name="Изображение товара2", null=True)
	image3 = models.ImageField(upload_to='products/', blank=True, verbose_name="Изображение товара3", null=True)
	image4 = models.ImageField(upload_to='products/', blank=True, verbose_name="Изображение товара4", null=True)
	video = EmbedVideoField(null=True, blank=True)
	description = HTMLField(blank=True, verbose_name="Описание")
	d_image = models.ImageField(upload_to='products/', blank=True, verbose_name="Рекламная картинка", null=True)
	d_text = models.CharField(max_length=100, blank=True, verbose_name='Текст на картинке', null=True)
	old_price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Старая цена", blank=True, null=True)
	price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name="Цена")
	stock = models.PositiveIntegerField(verbose_name="На складе")
	available = models.BooleanField(default=True, verbose_name="Доступен")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	pr_wi = models.ManyToManyField('self', blank=True, verbose_name='С этим товаром покупают')
	is_new = models.BooleanField(default=False, verbose_name='Новинка')
	is_hit = models.BooleanField(default=False, verbose_name='Хит')

	def get_absolute_url(self):
		return reverse('shop:ProductDetail', args=[self.category.slug, self.slug + '--' + str(self.id)])

	class Meta:
		ordering = ['name']
		verbose_name = 'Товар'
		verbose_name_plural = 'Товары'
		index_together = [
			['id', 'slug']
		]

	def __unicode__(self):
		return self.name

cart/forms.py
# -*- coding: utf-8 -*-
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]
class CartAddProductForm(forms.Form):
	quantity = forms.IntegerField(initial=1, widget=forms.TextInput( attrs = {'id': 'quanity-input', 'readonly': 'readonly','style': 'width: 20px; border: none; text-align:center;'} ))
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/forms.py
# -*- coding: utf-8 -*-
from django import forms

class ContactForm(forms.Form):
	phone = forms.CharField(required=True, max_length=30,label='Телефон')

class ContactEmailForm(forms.Form):
	email = forms.CharField(required=True, max_length=40, widget=forms.TextInput(attrs={'placeholder': 'Введите Email'}))

shop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from .models import Cat, Product, InfoModel, InfoModel1, Rent, SliderItem, Review, ContactEmail
from cart.forms import CartAddProductForm
from django.template import Context, Template, RequestContext
from django.db.models import Q
from cart.cart import ProductHistory
from django.template.loader import render_to_string
from django.http import HttpResponse
from shop.forms import ContactForm, ContactEmailForm
from django.http import HttpResponse,JsonResponse
from django.core.mail import EmailMessage


from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# def ProductList(request, Cat_slug=None):
#     return render(request, 'shop/product/product-list.html', {
#         'category': Cat_slug,
#     })

def ProductList(request, Cat_slug=None):
    cat = None
    product_list = Product.objects.all().order_by('-created')
    page = request.GET.get('page', 1)
    if Cat_slug and Cat_slug != 'all':
        cat = get_object_or_404(Cat, slug=Cat_slug)
        product_list = product_list.filter(category=cat)

    paginator = Paginator(product_list, 40)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    try:
        tree = cat.get_ancestors()
    except:
        tree = False
    try:
        tree_ch = cat.get_children()
    except:
        tree_ch = False
    
    return render(request, 'shop/product/product-list.html', {
        'tree': tree,
        'tree_ch': tree_ch,
        'category': cat,
        'products': products,
    })

def contactPhone(request):
    if request.is_ajax:
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            data = {
                'status': 'ok',
            }
            message = 'Телефон: ' + cd['phone']
            email = EmailMessage('Заявка на звонок', message, to=[InfoModel.objects.get(pk=1).email])
            email.send()
            return JsonResponse(data)
    return HttpResponse('ERORR')

def contactEmail(request):
    if request.is_ajax:
        form = ContactEmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            data = {
                'status': 'ok'
            }
            email_to = cd['email']
            message = InfoModel1.objects.get(pk=1).email_text
            ContactEmail.objects.create(email=email_to)
            email = EmailMessage('Подписка оформлена', message, to=[email_to])
            email.send()
            return JsonResponse(data)
    return HttpResponse('ERROR')


def search(request):
    question = request.GET.get('q')
    if question is not None:
        products = Product.objects.filter(Q(name__icontains=question)|Q(description__icontains=question))
        if products:
            return render(request, 'shop/product/search-success.html', {'products':products})
    return render(request, 'shop/product/search-not-fount.html')
    

def MainPage(request):
    new_products = Product.objects.filter(is_new=True)
    sale_products = Product.objects.filter(old_price__isnull=False)
    contact = ContactForm()
    emailForm = ContactEmailForm()
    cart_product_form = CartAddProductForm()
    slider_items = SliderItem.objects.all()
    history = ProductHistory(request)
    history_ids = list(history)[-4:]
    products_history = Product.objects.filter(id__in=history_ids).reverse()
    return render(request, 'shop/product/main-page.html', 
        {
        'new_products':new_products,
        'sale_products': sale_products,
        'cart_product_form': cart_product_form,
        'seo': InfoModel1.objects.get(pk=1).seo,
        'seo_title': InfoModel1.objects.get(pk=1).seo_title,
        'contact': contact,
        'emailForm': emailForm,
        'slider_items': slider_items,
        'reviews': Review.objects.all(),
        'pr_history': products_history,
        })

def ProductDetail(request, cat_slug, slug):
    history = ProductHistory(request)
    product = get_object_or_404(Product, id=int(slug.split('--')[1]), slug=slug.split('--')[0])
    history_ids = list(history)[-4:]
    history.add(product)
    products_history = Product.objects.filter(id__in=history_ids).reverse()
    cart_product_form = CartAddProductForm()
    try:
        tree = product.category.get_ancestors()
    except:
        tree = False


    
    return render(request, 'shop/product/detail.html', 
    	{'product': product,
        'tree': tree,
    	'cart_product_form': cart_product_form,
        'pr_history': products_history}) 



def contacts(request):
    template = 'shop/contacts.html'

    info = InfoModel1.objects.get(id=1).info
    rekv = InfoModel1.objects.get(id=1).rekv

    ctx = {
        'info1': info,
        'rekv': rekv,
    }
    return render(request, template, ctx)

def rent(request):
    rent = Rent.objects.all()
    return render(request, 'shop/rent.html', {'rents': rent})

def service(request):
    service = InfoModel1.objects.get(id=1).service
    return render(request, 'shop/service.html', {'service': service})

def shipping(request):
    return render(request, 'shop/shipping.html')

def garant(request):
    return render(request, 'shop/garant.html')

def about(request):
    return render(request, 'shop/about.html')

def vozvrat(request):
    return render(request, 'shop/vozvrat.html')

shop/templates/shop/product/product-list.html
{%extends 'shop/base.html'%}
{%load static%}
{% load mptt_tags %}
{%load tags%}
{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}

{%block content%}


<div class="container" style="margin-bottom: 3em">
    <div class="product-easy">
        {%if tree%}
            <a style="color: #FDA30E; text-decoration: none;" href="/all/">Каталог</a> >
            {% for node in tree %}
                <a style="color: #FDA30E; text-decoration: none;" href="{{node.get_absolute_url}}">{{node.name}}</a> > 
            {% endfor %}
            <b>{{category.name}}</b>
        {%else%}
            {%if category%}
                <a style="color: #FDA30E; text-decoration: none;" href="/all/">Каталог</a> >
                <b>{{category.name}}</b>
            {%endif%}
        {%endif%}
        <div style="display: flex; flex-wrap: wrap; margin-bottom: 2em; justify-content: center;">
            <h1 style="border-bottom: 3px solid orange;">
                {% if category %} {{ category.name }} {% else %} Каталог {% endif %}
            </h1>
        </div>

        {%if products%}
            {%products_list products%}
        {%else%}
            {%if tree_ch%}
                {%for node in tree_ch%}
                    <a href="{{ node.get_absolute_url }}">
                        <div class="col-md-3 product-men">
                            <div class="men-pro-item simpleCart_shelfItem">
                                {%if node.image%}<img class="img-responsive" style="object-fit: cover; height: 250px;" src="{{node.image.url}}" alt="">{%endif%}
                                <div style="height: 40px;" class="item-info-product ">
                                    <h3 style="color: orange; font-size: 1.2em">{{ node.name }}</h3>
                                </div>
                            </div>
                        </div>
                    </a>
                {%endfor%}
            {%endif%}
        {%endif%}
    </div>
</div>
{%endblock%}

shop/templates/shop/product/search-not-fount.html
{%extends "shop/base.html"%}
{%load static%}

{%block title %} Поиск {%endblock%}

{%block content%}
<div class="product-easy">
	<div class="container">
		<div class=""><h1 style="text-align: center; margin-bottom: 2em; border-bottom: 3px solid orange; padding: 1em; ">Результаты поиска</h1></div>
		<br>
		<br>
		<div class=""><h2 style="text-align: center; margin-bottom: 2em; padding: 1em; ">По вашему запросу нет ни одного совпадения</h2></div>

	</div>
</div>
{%endblock%}

shop/templates/shop/product/search-success.html
{%extends "shop/base.html"%}
{%load static%}

{%block title %} Поиск {%endblock%}

{%block content%}
<div class="product-easy">
        <style>
    #id_quantity, label {
        display: none;

    } 
</style>
	<div class="container">
		<div class=""><h1 style="text-align: center; margin-bottom: 2em; border-bottom: 3px solid orange; padding: 1em; ">Результаты поиска</h1></div>

                        {% for product in products %}
                        <div class="col-md-3 product-men">
                            <div class="men-pro-item simpleCart_shelfItem">
                                <div class="men-thumb-item">
                                    <img style="object-fit: cover; height: 250px;" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "shop/images/no-img.jpg"%}{% endif %}" alt="" class="pro-image-front">
                                    <img style="object-fit: cover; height: 250px;" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "shop/images/no-img.jpg"%}{% endif %}" alt="" class="pro-image-back">
                                    <div class="men-cart-pro">
                                        <div class="inner-men-cart-pro">
                                            <a href="{{ product.get_absolute_url }}" class="link-product-add-cart">Посмотреть</a>
                                        </div>
                                    </div>
                                    <div class="top-labels">
                                            {%if not product.available %} <span class="prom not-available">предзаказ</span> {%else%}{%endif%}
                                            {%if product.old_price %} <span class="prom sale">Акция</span> {%else%}{%endif%}
                                            {%if product.is_hit %} <span class="prom hit">Хит</span> {%else%}{%endif%}
                                            {%if product.is_new %} <span class="prom new">Новинка</span> {%else%}{%endif%}
                                        </div>
                                </div>
                                <div class="item-info-product ">
                                    <h4><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
                                    <div class="info-product-price">
                                        <span class="item_price">{{ product.price }} руб.</span>
                                    </div>
            <div class="occasion-cart">
                  <form id="cart__form_{{product.id}}" action="{% url "cart:CartAdd" product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <button type="submit" onclick="javascript:ajaxSubmit($(this.form))" class="item_add hvr-outline-out button2"> Добавить В корзину </button>
</form>
          </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="clearfix"></div>
	</div>
</div>
{%endblock%}