cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
	url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
	url(r'^$', views.CartDetail, name='CartDetail'),
]

orders/urls.py
from django.conf.urls import url, include
from . import views
from django.views.generic import TemplateView
from .views import OrderPage
urlpatterns = [
	url(r'^create/$', views.OrderCreate, name='OrderCreate'),
	url(r'payment-form/$', OrderPage.as_view(), name='payment_form'),
	url(r'^fail-payment/$', TemplateView.as_view(template_name='fail.html'), name='payment_fail'),
	url(r'^success-payment/$', TemplateView.as_view(template_name='success.html'), name='payment_success'),
	url(r'^yandex-money/', include('yandex_money.urls')),
]

orders/models.py
# -*- coding: utf-8 -*-
from django.db import models

from shop.models import Product

class Order(models.Model):
	first_name = models.CharField(verbose_name='Имя', max_length=50)
	last_name = models.CharField(verbose_name='Фамилия', max_length=50)
	email = models.EmailField(verbose_name='Email')
	street =  models.CharField(verbose_name='Улица', max_length=250, null=True)
	city = models.CharField(verbose_name='Город', max_length=100)
	phone = models.CharField(verbose_name='Телефон', max_length=20, null=True)
	building = models.CharField(verbose_name='dom', max_length=20, null=True)
	aps = models.CharField(verbose_name="Квартира", max_length=10, null=True)
	delivery_choice = models.CharField(verbose_name='Способ доставки', max_length=50, null=True)
	paid_choice = models.CharField(max_length=100, null=True)
	created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
	updated = models.DateTimeField(verbose_name='Обновлен', auto_now=True)
	paid = models.BooleanField(verbose_name='Оплачен', default=False)

	class Meta:
		ordering = ('-created', )
		verbose_name = 'Заказ'
		verbose_name_plural = 'Заказы'

	def __str__(self):
		return 'Заказ: {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
	order = models.ForeignKey(Order, related_name='items')
	product = models.ForeignKey(Product, related_name='order_items')
	price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(verbose_name='Количество', default=1)

	def __str__(self):
		return '{}'.format(self.id)

	def get_cost(self):
		return self.price * self.quantity

orders/forms.py
# -*- coding: utf-8 -*-
from django import forms
from orders.models import Order

CHOICES = (('1', 'Оплата наличными'), ('2', 'Электронными деньгами (сбербанк онлайн)'))
dCHOICE = (('1', 'Самовывоз'), ('350', 'Доставка по г.Москве — 350 рублей'), ('0', 'Доставка по г.Одинцово — бесплатно (при заказе от 5000 рублей)'), ('370','Доставка по Москвой области — 350 рублей + 20руб/км от МКАД'))
class OrderCreateForm(forms.ModelForm):
	paid_choice = forms.ChoiceField(choices=CHOICES,widget=forms.RadioSelect)
	delivery_choice = forms.ChoiceField(choices=dCHOICE, widget=forms.RadioSelect)
	class Meta:
		model = Order
		fields = ['first_name','delivery_choice','building','last_name', 'email', 'paid_choice', 'phone' ,'street', 'aps',
				  'city']

orders/views.py
# -*- coding: utf-8 -*-
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from .models import OrderItem, Order
from decimal import Decimal
from .forms import OrderCreateForm
from cart.cart import Cart
from django.views.generic import TemplateView
from yandex_money.forms import PaymentForm
from yandex_money.models import Payment
from shop.models import InfoModel
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives
from . import forms
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
def OrderCreate(request):
	cart = Cart(request)
	if len(cart) > 0:
		if request.method == 'POST':
			form = OrderCreateForm(request.POST)
			if form.is_valid():

				order = form.save()
				request.session['order_id'] = order.id
				for item in cart:
					OrderItem.objects.create(order=order, product=item['product'],
											 price=item['price'],
											 quantity=item['quantity'])
				cart.clear()
				OrderCreated(order.id)
				return render(request, 'orders/order/created.html', {'id': order.id})

	form = OrderCreateForm()
	return render(request, 'orders/order/create.html', {'cart': cart,
														'form': form})

def OrderCreated(order_id):
	order = Order.objects.get(id=order_id)
	delivery = ''
	payment = ''
	itogo = order.get_total_cost() + int(order.delivery_choice)
	for i in forms.dCHOICE:
		if i[0] == str(order.delivery_choice):
			delivery = i[1]
	for i in forms.CHOICES:
		if i[0] == str(order.paid_choice):
			payment = i[1]
	subject, from_email, to = 'Детали заказа #' + str(order.id), settings.DEFAULT_FROM_EMAIL, order.email
	html_content = render_to_string('orders/order_mail.html', {'itogo': itogo,'order': order, 'payment': payment, 'delivery': delivery, 'items': OrderItem.objects.filter(order=order)})
	text_content = strip_tags(html_content)

	msg = EmailMultiAlternatives(subject, text_content, from_email, [to, InfoModel.objects.get(pk=1).email])
	msg.attach_alternative(html_content, "text/html")
	msg.send()


class OrderPage(TemplateView):
	template_name = 'orders/order_page.html'
	
	def get_context_data(self, **kwargs):
		order_id = self.request.session.get('order_id')
		order = get_object_or_404(Order, id=order_id)
		items = OrderItem.objects.filter(order=order)
		payment = Payment(order_amount=order.get_total_cost().quantize(Decimal('.01')))
		payment.save()

		ctx = super(OrderPage, self).get_context_data(**kwargs)
		ctx['form'] = PaymentForm(instance=payment)
		ctx['items'] = items
		return ctx

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
  Оформление заказа
{% endblock %}

{% block content %}
<style>
  h2, ul{
    margin-bottom: 1.5em;
  }
  li {
    margin: .5em 0;
  }
  label {
    display: block;
  }
  .form-control {
    margin-bottom: 1em;
  }
  .form-select-delivery {
    margin-bottom: 1em;
  }
  .block-minicart {
    width: 100%;
    background-color: #F7F7F7;
  }
  .block-minicart {
    padding: 1.5em;
    margin-top: 55px;
  }
  .block-minicart .title{
    width: 65%;
    padding-right: 20px;
    text-align: left;
    /* padding-top: 10px; */
    font-size: 12px;
    font-weight: bold;
    line-height: 13px;
    height: 40px;
  }
  .block-minicart .price {
    padding-left: .5em;
    text-align: right;
    /* padding-top: 10px; */
    font-size: 14px;
    font-weight: normal;
    line-height: 1;
    margin-bottom: 0;
    clear: left;
  }


</style>

 <div style="margin-top:4em;" class="container">
  <form action="/order/create/" class="order" method="POST">{% csrf_token %}
        <div class="col-sm-12">
    <div class="row">
      <div class="col-md-8">
        <h2>Как и где вы хотите получить заказ?</h2>
        <div class="form-select-delivery">
          <div class="col-md-9">
                        <ul style="list-style: none;" id="id_delivery_choice">
                <li>
                    <label for="id_delivery_choice_1">
                        <input type="radio" name="delivery_choice" value="350" required="" id="id_delivery_choice_1"> Доставка по г.Москве — 350 рублей</label>
                </li>
                                <li>
                    <label for="id_delivery_choice_3">
                        <input type="radio" name="delivery_choice" value="370" required="" id="id_delivery_choice_3"> Доставка по Московской области — 350 рублей + 20руб/км от МКАД</label>
                </li>
            </ul>
            <p style="color: #9F9F9F; font-size: .9em; margin: 1em 0;">Доставка осуществляется в течение 2-х дней. Возможно предварительное оформление заказа</p>
          </div>

        </div>
        <div class="address-hidden">
          <div class="form-group input-parent">
            <div class="col-sm-9">
              <input type="text" placeholder="Город" name="city" class="form-control" required="" id="id_city" maxlength="100">
            </div>
          </div>
          <div class="form-group input-parent">
            <div class="col-md-9">
              <div class="row">
                <div class="col-md-6">
                  <input type="text" name="street" placeholder="Улица" class="form-control" required="" id="id_street" maxlength="250">
                </div>
                <div class="col-md-3">
                  <input type="text" id="id_building" placeholder="Дом" name="building" value="" required="" class="form-control">
                </div>
                <div class="col-md-3">
                  <input type="text" name="aps"  placeholder="Квартира" class="form-control" required="" id="id_aps" maxlength="10">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-9">
            <h2>Как вам будет удобно оплатить заказ?</h2>
            <ul style="list-style: none;" id="id_paid_choice">
                <li>
                    <label for="id_paid_choice_0">
                        <input type="radio" name="paid_choice" value="1" required="" id="id_paid_choice_0"> Оплата наличными</label>
                </li>
                <li>
                    <label for="id_paid_choice_1">
                        <input type="radio" name="paid_choice" value="2" required="" id="id_paid_choice_1"> Электронными деньгами (сбербанк онлайн)</label>
                </li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-9">
            <h2>Укажите ваши личные данные</h2>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-6">
                <input type="text" placeholder="Имя" name="first_name" required="" id="id_first_name" maxlength="50" class="form-control">
              </div>
              <div class="col-md-6">
                <input type="text" placeholder="Фамилия" name="last_name" required="" id="id_last_name" maxlength="50" class="form-control">
              </div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-6">
                <input type="email" placeholder="Email" name="email" required="" id="id_email" maxlength="254" class="form-control">
              </div>
              <div class="col-md-6">
                <input type="text" placeholder="Телефон" name="phone" required="" id="id_phone" maxlength="20" class="form-control">
              </div>
            </div>
          </div>
        </div>
        <div style="text-align: right;"><button style="margin-bottom: 1em;" id="sbmBtn" type="submit" class="item_add hvr-outline-out button2" value="">Оформить</button></div>
      </div>
      <div class="col-md-4">
    <div class="block-minicart">
      <table>
        <tbody>
        {% for item in cart  %}
          <tr>
            <td class="title">
              {{ item.product.name }}
            </td>
            <td class="count">
              {{ item.quantity }} шт
            </td>
            <td class="price">
              {{ item.total_price }} P
            </td>
          </tr>
          {% endfor %}
          <tr class="footer">
            <th class="total">
              Итого:
              <span id="total_cost"><strong>{{cart.get_total_price}}</strong> P</span>
            </th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

    </div>


      

  </div>


  </form>

 </div>
<script type="text/javascript">
var last_price = parseInt($('#total_cost strong').text());
$('input[name=delivery_choice]').change(function(){
var value = parseInt($( 'input[name=delivery_choice]:checked' ).val());
$('#total_cost strong').text(last_price + value);
});

</script>


{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
  Спасибо за заказ
{% endblock %}


{%block content%}
<style>
  label {
    display: block;
  }
</style>
<div class="container">
   <div class=""><h1 style="text-align: center; margin-bottom: 2em; border-bottom: 3px solid orange; padding: 2em; ">Спасибо за заказ</h1></div>
<div class="product-easy" style="display: flex; flex-direction: row; justify-content: center;">
<h1>Идентификатор вашего заказа: {{ id }}. В течение нескольких минут, наш менеджер с Вами свяжется.</h1>
</div>
</div>
 
  


{% endblock %}